### ISSUE TITLE
How to use this repo?

### ISSUE THREAD

**Issue by wzy1845** [dexXxed/abnormal-event-detection#2]
Thank you very much for your code!
Is the backend of keras tensorflow or theano?
In what order should the code be executed? 
Any help would be appreciated.

**Comment by dexXxed** [comment]
Hello!

**Comment by dexXxed** [comment]
Hello

**Comment by dexXxed** [comment]
Hello!
I am glad to see you here in this repository!
To be honest, main code of this repo is [here](https://github.com/ptirupat/AnomalyDetection_CVPR18)

I had just remade some logic (in visualization of `matplotlib`, loading model to Git LFS and code refactoring).

As in the original code there is logic of both `tensorflow` and `theano`

In `configuration.py` there is variable `sample_video_path`, which is name of any video from [this dataset](https://webpages.uncc.edu/cchen62/dataset.html)

To run this code you have to run `test_detect.py` and it will draw beautiful visualize of abnormal events here in given video.

If there are any questions, I will be glad to answer!
Have a nice day!
