### ISSUE TITLE
Hi, thank you for your work, but I did not find the training code?

### ISSUE THREAD

**Issue by XUYUNYUN666** [dexXxed/abnormal-event-detection#3]

**Comment by dexXxed** [comment]
Hello!
I am glad to see you here in this repository!
To be honest, main code of this repo is [here](https://github.com/ptirupat/AnomalyDetection_CVPR18)

In the original repo there is no training code provided ([issue about this](https://github.com/ptirupat/AnomalyDetection_CVPR18/issues/10))
