### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by remindof** [dexXxed/abnormal-event-detection#6]
Good day! Thank you for your excellent work! It really helps a lot.

I noticed that there is a file "AI_Train.py", which does not exist in the paper's original code. May I ask:

- Is this the code for training on other datasets?
- Did you train the models "weights.mat", "weights_L1L2.mat" by yourself? If so, what is your training dataset? The whole UCF-Crime or just part of it?

Thank you:)

**Comment by yutianshifengmang** [comment]
Hello, author, thank you for your work: Please ask me to install the environment according to the environment information you provided, but it can't run. What's the matter?

**Comment by yutianshifengmang** [comment]
`Using TensorFlow backend.
Number of clips in the video :  173
WARNING:tensorflow:From F:\install_work_software\anaconda3\envs\myenv01\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "F:/abnormal-event-detection-master/test_detect.py", line 54, in <module>
    run_demo()
  File "F:/abnormal-event-detection-master/test_detect.py", line 17, in run_demo
    feature_extractor = c3d_feature_extractor()
  File "F:\abnormal-event-detection-master\c3d.py", line 86, in c3d_feature_extractor
    model = C3D()
  File "F:\abnormal-event-detection-master\c3d.py", line 80, in C3D
    model.load_weights(cfg.c3d_model_weights)
  File "F:\install_work_software\anaconda3\envs\myenv01\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "F:\install_work_software\anaconda3\envs\myenv01\lib\site-packages\keras\engine\network.py", line 1221, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "F:\install_work_software\anaconda3\envs\myenv01\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "F:\install_work_software\anaconda3\envs\myenv01\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)`


The error is shown above

**Comment by Panlizhi** [comment]
@yutianshifengmang  i also meet this error, i don't know how to fix it........

**Comment by remindof** [comment]
Dear both @yutianshifengmang @Panlizhi , did you try to download the C3D model manually? 

The .h5 file in this repo is not the real .h5 file to be used in training. Please download it somewhere else, replace c3d_sports1m.h5 model and try again.

**Comment by Panlizhi** [comment]
thanks bro, but.....where can i download  the right .h5 file? thank you.

**Comment by Panlizhi** [comment]
@remindof thanks bro, but.....where can i download the right .h5 file? thank you.

**Comment by yutianshifengmang** [comment]
Thank you, I have solved the problem, thank you again!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dexXxed/abnormal-event-detection"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月21日(星期一) 晚上10:03
收件人:&nbsp;"dexXxed/abnormal-event-detection"<abnormal-event-detection@noreply.github.com&gt;;
抄送:&nbsp;"伍怀洪"<2032256568@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dexXxed/abnormal-event-detection] Training dataset (#6)





 
Dear both @yutianshifengmang @Panlizhi , did you try to download the C3D model manually?
 
The .h5 file in this repo is not the real .h5 file to be used in training. Please download it somewhere else, replace c3d_sports1m.h5 model and try again.

**Comment by Panlizhi** [comment]
@yutianshifengmang excuse me.how did you solve it?

**Comment by yutianshifengmang** [comment]
I have nearly solved this problem. All I need to do is download a C3D model file and put it in the trained_models folder.The following is the connection of the file that I uploaded to the network disk.






Connection：https://pan.baidu.com/s/1JhzcmINGRVJXhub0wRDB_w&nbsp;
code：51t1&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dexXxed/abnormal-event-detection"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月21日(星期一) 晚上10:16
收件人:&nbsp;"dexXxed/abnormal-event-detection"<abnormal-event-detection@noreply.github.com&gt;;
抄送:&nbsp;"伍怀洪"<2032256568@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dexXxed/abnormal-event-detection] Training dataset (#6)





 
@remindof thanks bro, but.....where can i download the right .h5 file? thank you.

**Comment by yutianshifengmang** [comment]
I have nearly solved this problem. All I need to do is download a C3D model file and put it in the trained_models folder.The following is the connection of the file that I uploaded to the network disk.






Connection：https://pan.baidu.com/s/1JhzcmINGRVJXhub0wRDB_w
code：51t1








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dexXxed/abnormal-event-detection"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月21日(星期一) 晚上10:30
收件人:&nbsp;"dexXxed/abnormal-event-detection"<abnormal-event-detection@noreply.github.com&gt;;
抄送:&nbsp;"伍怀洪"<2032256568@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dexXxed/abnormal-event-detection] Training dataset (#6)





 
@yutianshifengmang excuse me.how did you solve it?
